export const SOURCE_TIERS = {
  tier1: [
    "carbon180.org",
    "cdrprimer.org",
    "cdr.fyi",
    "carbonbrief.org",
    "isometric.com",
    "verra.org",
    "goldstandard.org",
    "puro.earth",
    "unfccc.int",
    "climatechangenews.com",
    "carbonpulse.com",
    "qcintel.com",
    "carbonherald.com",
    "biochartoday.com",
  ],
  tier2: [
    "canarymedia.com",
    "greenbiz.com",
    "techcrunch.com",
    "axios.com",
    "nature.com",
    "science.org",
    "pnas.org",
    "iopscience.iop.org",
    "agupubs.onlinelibrary.wiley.com",
    "insideclimatenews.org",
    "e360.yale.edu",
    "ctvc.co",
  ],
  tier3: [
    "theguardian.com",
    "bbc.co.uk",
    "reuters.com",
    "npr.org",
    "nytimes.com",
    "bloomberg.com",
    "ft.com",
    "wsj.com",
    "forbes.com",
    "scientificamerican.com",
    "grist.org",
    "desmog.com",
    "sustainabilitymag.com",
  ],
} as const;

export const REQUIRED_RELEVANCE_TERMS = [
  "carbon removal",
  "carbon dioxide removal",
  "cdr",
  "enhanced weathering",
  "enhanced rock weathering",
  "erw",
  "biochar",
  "mrv",
  "permanence",
  "additionality",
  "carbon credit",
  "carbon credits",
  "voluntary carbon market",
  "issuance",
  "retirement",
  "registry",
  "article 6",
  "corsia",
  "cbam",
  "eu ets",
  "direct air capture",
  "dac",
  "beccs",
  "basalt",
  "alkalinity",
  "mineralization",
  "geochemistry",
  "soil",
  "farmland",
  "offtake",
  "procurement",
];

export const BOOST_TERMS = [
  "study",
  "paper",
  "preprint",
  "methodology",
  "protocol",
  "validation",
  "verification",
  "series a",
  "series b",
  "funding",
  "investment",
  "grant",
  "million",
  "billion",
  "frontier",
  "microsoft",
  "stripe",
];

export const EXCLUDE_TERMS = [
  "ev charging",
  "solar panel",
  "wind turbine",
];

export const STREAM_RSS_FEEDS: Record<
  "policy" | "funding" | "market" | "research" | "customer" | "competitive",
  string[]
> = {
  policy: [
    "https://www.climatechangenews.com/feed/",
    "https://feeds.feedburner.com/carbonbrief",
    "https://rss.nytimes.com/services/xml/rss/nyt/Climate.xml",
  ],
  funding: [
    "https://www.ctvc.co/feed",
    "https://www.ft.com/climate-change?format=rss",
    "https://techcrunch.com/tag/sustainability/feed/",
  ],
  market: [
    "https://carbonherald.com/feed/",
    "https://www.theguardian.com/environment/rss",
    "https://feeds.bbci.co.uk/news/science_and_environment/rss.xml",
  ],
  research: [
    "https://www.nature.com/nclimate.rss",
    "https://feeds.feedburner.com/carbonbrief",
    "https://insideclimatenews.org/feed/",
    "https://biochartoday.com/category/news/feed/",
  ],
  customer: [
    "https://biochartoday.com/feed/",
    "https://www.canarymedia.com/feed",
    "https://www.theguardian.com/environment/rss",
  ],
  competitive: [
    "https://techcrunch.com/tag/climate/feed/",
    "https://techcrunch.com/tag/sustainability/feed/",
    "https://www.theverge.com/rss/climate/index.xml",
  ],
};
