export const SOURCE_TIERS = {
  tier1: [
    "carbon180.org",
    "cdrprimer.org",
    "cdr.fyi",
    "carbonbrief.org",
    "isometric.com",
    "verra.org",
    "goldstandard.org",
    "puro.earth",
    "unfccc.int",
    "climatechangenews.com",
    "carbonpulse.com",
    "qcintel.com",
    "carbonherald.com",
    "biochartoday.com",
    "carboncredits.com",
    "voluntarycarbonmarket.org",
    "climatetrade.com",
    "southpole.com",
    "climeworks.com",
    "heirloomcarbon.com",
    "lithos.earth",
    "charm.industries",
    "runningtide.com",
    "44.01",
  ],
  tier2: [
    "canarymedia.com",
    "greenbiz.com",
    "techcrunch.com",
    "axios.com",
    "nature.com",
    "science.org",
    "pnas.org",
    "iopscience.iop.org",
    "agupubs.onlinelibrary.wiley.com",
    "insideclimatenews.org",
    "e360.yale.edu",
    "ctvc.co",
    "sifted.eu",
    "cleantech.com",
    "energymonitor.ai",
    "mongabay.com",
    "theenergymix.com",
    "edie.net",
    "environmental-finance.com",
    "ecosystemmarketplace.com",
  ],
  tier3: [
    "theguardian.com",
    "bbc.co.uk",
    "reuters.com",
    "npr.org",
    "nytimes.com",
    "bloomberg.com",
    "ft.com",
    "wsj.com",
    "forbes.com",
    "scientificamerican.com",
    "grist.org",
    "desmog.com",
    "sustainabilitymag.com",
    "cnbc.com",
    "politico.eu",
    "thehill.com",
    "wired.com",
  ],
} as const;

/** Flat list of all trusted domains for Exa includeDomains filter. */
export const ALL_TRUSTED_DOMAINS: string[] = [
  ...SOURCE_TIERS.tier1,
  ...SOURCE_TIERS.tier2,
  ...SOURCE_TIERS.tier3,
  // Academic & institutional
  "economist.com",
  "iea.org",
  "worldbank.org",
  "imf.org",
  "arxiv.org",
  "frontierclimate.com",
  "spglobal.com",
  "mcgill.ca",
  "mit.edu",
  "ox.ac.uk",
  "cam.ac.uk",
  "stanford.edu",
  "iisc.ac.in",
  "ashoka.edu.in",
  "gov.uk",
  "europa.eu",
  "epa.gov",
  "energy.gov",
  "eartharxiv.org",
  "mdpi.com",
  "cdm.unfccc.int",
  "link.springer.com",
  "springer.com",
  "business-standard.com",
  "fortuneindia.com",
  "news.un.org",
  "c2es.org",
];

/** Per-stream Exa domain overrides — narrows search to most relevant sources per stream. */
export const STREAM_EXA_DOMAINS: Record<string, string[]> = {
  policy: [
    "carbonbrief.org", "climatechangenews.com", "carbonpulse.com", "carbonherald.com",
    "unfccc.int", "europa.eu", "gov.uk", "epa.gov", "energy.gov", "politico.eu",
    "thehill.com", "reuters.com", "bloomberg.com", "ft.com", "nytimes.com",
    "theguardian.com", "insideclimatenews.org", "climeworks.com",
  ],
  funding: [
    "ctvc.co", "techcrunch.com", "sifted.eu", "axios.com", "bloomberg.com", "ft.com",
    "reuters.com", "forbes.com", "cnbc.com", "greenbiz.com", "canarymedia.com",
    "cleantech.com", "carboncredits.com", "frontierclimate.com", "energymonitor.ai",
  ],
  market: [
    "carbonpulse.com", "carbonherald.com", "carboncredits.com", "cdr.fyi",
    "ecosystemmarketplace.com", "environmental-finance.com", "verra.org",
    "goldstandard.org", "puro.earth", "isometric.com", "qcintel.com",
    "reuters.com", "bloomberg.com", "spglobal.com", "greenbiz.com",
  ],
  research: [
    "nature.com", "science.org", "pnas.org", "arxiv.org", "eartharxiv.org",
    "mdpi.com", "link.springer.com", "iopscience.iop.org",
    "agupubs.onlinelibrary.wiley.com", "carbonbrief.org", "biochartoday.com",
    "e360.yale.edu", "scientificamerican.com", "mit.edu", "stanford.edu",
  ],
  customer: [
    "biochartoday.com", "canarymedia.com", "greenbiz.com", "reuters.com",
    "bloomberg.com", "ft.com", "forbes.com", "carboncredits.com", "carbonherald.com",
    "frontierclimate.com", "business-standard.com", "fortuneindia.com",
    "edie.net", "sustainabilitymag.com", "cnbc.com",
  ],
  competitive: [
    "techcrunch.com", "sifted.eu", "axios.com", "carbonherald.com", "carboncredits.com",
    "cleantech.com", "greenbiz.com", "canarymedia.com", "isometric.com", "cdr.fyi",
    "verra.org", "goldstandard.org", "puro.earth", "wired.com", "forbes.com",
  ],
};

export const REQUIRED_RELEVANCE_TERMS = [
  // Core CDR & carbon
  "carbon removal",
  "carbon dioxide removal",
  "cdr",
  "carbon credit",
  "carbon credits",
  "carbon market",
  "carbon offset",
  "carbon capture",
  "carbon sequestration",
  "carbon storage",
  "carbon sink",
  "carbon intensity",
  "carbon pricing",
  "carbon tax",
  "carbon border",
  "carbon negative",
  "negative emissions",
  "net zero",
  "net-zero",
  "decarbonization",
  "decarbonisation",
  // Methods & technologies
  "enhanced weathering",
  "enhanced rock weathering",
  "erw",
  "biochar",
  "direct air capture",
  "dac",
  "beccs",
  "bioenergy",
  "blue carbon",
  "ocean alkalinity",
  "soil carbon",
  "afforestation",
  "reforestation",
  "nature-based solution",
  "nature-based",
  // MRV & standards
  "mrv",
  "permanence",
  "additionality",
  "verification",
  "methodology",
  "issuance",
  "retirement",
  "registry",
  // Policy & compliance
  "article 6",
  "corsia",
  "cbam",
  "eu ets",
  "voluntary carbon market",
  "vcm",
  "compliance market",
  "emission trading",
  "emissions trading",
  "scope 1",
  "scope 2",
  "scope 3",
  // Science terms
  "basalt",
  "alkalinity",
  "mineralization",
  "geochemistry",
  "co2 removal",
  "ghg",
  "greenhouse gas",
  // Commercial
  "offtake",
  "procurement",
  "farmland",
  "climate tech",
  "cleantech",
  "carbon finance",
  "green bond",
  "sustainability-linked",
  "climate finance",
];

export const BOOST_TERMS = [
  "study",
  "paper",
  "preprint",
  "methodology",
  "protocol",
  "validation",
  "verification",
  "series a",
  "series b",
  "funding",
  "investment",
  "grant",
  "million",
  "billion",
  "frontier",
  "microsoft",
  "stripe",
  "jpmorgan",
  "google",
  "shopify",
  "airbus",
  "swiss re",
  "nextgen",
];

export const EXCLUDE_TERMS = [
  "ev charging",
  "solar panel",
  "wind turbine",
  "cryptocurrency mining",
  "nft",
  "meme coin",
];

export const STREAM_RSS_FEEDS: Record<
  "policy" | "funding" | "market" | "research" | "customer" | "competitive",
  string[]
> = {
  policy: [
    "https://www.climatechangenews.com/feed/",
    "https://feeds.feedburner.com/carbonbrief",
    "https://rss.nytimes.com/services/xml/rss/nyt/Climate.xml",
    "https://insideclimatenews.org/feed/",
    "https://grist.org/feed/",
    "https://desmog.com/feed",
    "https://www.theguardian.com/environment/climate-crisis/rss",
    "https://carboncredits.com/feed/",            // carbon policy news
    "https://carbon180.org/feed",                  // CDR policy advocacy
    "https://carbonherald.com/feed/",              // carbon industry news
    "https://news.un.org/feed/subscribe/en/news/topic/climate-change/feed/rss.xml", // UN climate
    "https://www.c2es.org/feed/",                  // Center for Climate and Energy Solutions
  ],
  funding: [
    "https://www.ctvc.co/feed",                    // climate VC newsletter
    "https://www.ft.com/climate-change?format=rss",
    "https://techcrunch.com/tag/sustainability/feed/",
    "https://techcrunch.com/tag/climate/feed/",
    "https://www.greenbiz.com/feed",
    "https://www.canarymedia.com/feed",
    "https://carbonherald.com/feed/",
    "https://carboncredits.com/feed/",             // carbon finance deals
    "https://energymonitor.ai/feed/",              // energy transition funding
    "https://carbon180.org/feed",                  // CDR funding advocacy
    "https://www.ecosystemmarketplace.com/feed/",  // market finance
    "https://www.cnbc.com/id/10000108/device/rss/rss.html", // CNBC environment
  ],
  market: [
    "https://carbonherald.com/feed/",
    "https://carbonherald.com/category/carbon-markets/feed", // carbon markets specific
    "https://carboncredits.com/feed/",             // carbon credit pricing/trading
    "https://www.ecosystemmarketplace.com/feed/",  // VCM marketplace
    "https://feeds.feedburner.com/carbonbrief",
    "https://www.greenbiz.com/feed",
    "https://energymonitor.ai/feed/",
    "https://www.theguardian.com/environment/rss",
    "https://feeds.bbci.co.uk/news/science_and_environment/rss.xml",
  ],
  research: [
    "https://www.nature.com/nclimate.rss",
    "https://www.nature.com/nenergy.rss",
    "https://www.nature.com/ngeo.rss",
    "https://feeds.feedburner.com/carbonbrief",
    "https://insideclimatenews.org/feed/",
    "https://biochartoday.com/category/news/feed/",
    "https://carbon180.org/feed",                  // CDR research highlights
    "https://www.edie.net/feed/",                  // sustainability research
  ],
  customer: [
    "https://biochartoday.com/feed/",
    "https://carboncredits.com/feed/",             // buyer/offtake news
    "https://carbonherald.com/feed/",
    "https://www.canarymedia.com/feed",
    "https://www.greenbiz.com/feed",
    "https://www.edie.net/feed/",                  // corporate sustainability
    "https://energymonitor.ai/feed/",
    "https://www.theguardian.com/environment/rss",
    "https://www.business-standard.com/rss/companies/news-102.rss",
    "https://www.fortuneindia.com/feed",
  ],
  competitive: [
    "https://techcrunch.com/tag/climate/feed/",
    "https://techcrunch.com/tag/sustainability/feed/",
    "https://carbonherald.com/feed/",
    "https://carboncredits.com/feed/",             // competitor launches
    "https://carbon180.org/feed",                  // CDR landscape
    "https://www.greenbiz.com/feed",
    "https://www.canarymedia.com/feed",
    "https://www.ctvc.co/feed",
    "https://energymonitor.ai/feed/",
    "https://www.ecosystemmarketplace.com/feed/",
    "https://www.edie.net/feed/",
  ],
};
